StoreApp/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StoreApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StoreApp/Areas/Admin/Controllers/ProductController.cs
using Entities.Dtos;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.Categories = GetCategoriesSelectList();
            return View();
        }

        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetAllCategories(false),
                "CategoryId",
                "CategoryName",
                "1");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] ProductDtoForInsertion product)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            _manager.ProductService.CreateOneProduct(product);
            return RedirectToAction("Index");
        }

        public IActionResult Update([FromRoute(Name = "id")] int id)
        {
            ViewBag.Categories = GetCategoriesSelectList();
            var model = _manager.ProductService.GetOneProductUpdate(id, false);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([FromForm]ProductDtoForUpdate product)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            _manager.ProductService.UpdateOneProduct(product);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete([FromRoute(Name = "id")] int id)
        {
            _manager.ProductService.DeleteOneProduct(id);
            return RedirectToAction("Index");
        }
    }
}

StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetAllCategories(false);
            return View(categories);
        }
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name ="id")]int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Category/Index.cshtml
<h3>Category Index</h3>

StoreApp/Areas/Admin/Views/Dashboard/Index.cshtml
<h3>Dashboard Index</h3>

StoreApp/Areas/Admin/Views/Product/Create.cshtml
@model ProductDtoForInsertion

<div class="text-center">
    <div class="display-6">Create</div>
</div>
<form method="post" asp-action="Create">
    <div class="form-group my-3">
        <label asp-for="CategoryId"></label>
        <select class="form-control" asp-items="@ViewBag.Categories" asp-for="CategoryId">
        </select>
    </div>
    <div class="form-group my-3">
        <div class="text-danger" asp-validation-summary="All">
        </div>
        <label asp-for="ProductName">Product Name</label>
        <input asp-for="ProductName" class="form-control" />
    </div>
    <div class="form-group my-3">
        <label asp-for="Price">Product Name</label>
        <input asp-for="Price" class="form-control" />
    </div>
    <div class="form-group my-3">
        <div class="btn-group">
        <button class="btn btn-primary" type="submit">
            <i class="fa fa-save"></i>
            Save
            </button>
            <a asp-action="Index" class="btn btn-outline-primary">
                <i class="fa fa-list"></i>
                Products</a>
        </div>
    </div>
</form>

StoreApp/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<Product>
<div class="text-center">
    <div class="display-6">Products</div>

    <div class="d-flex justify-content-end my-3">
        <a class="btn btn-outline-success" asp-action="Create">
            <i class="fa fa-plus"></i>
            Create
            </a>
    </div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Product prd in Model)
            {
                <tr>
                    <td>@prd.ProductId</td>
                    <td>@prd.ProductName</td>
                    <td>@prd.Price.ToString("C")</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-warning" asp-action="Update" asp-route-id="@prd.ProductId">
                                <i class="fa fa-edit"></i>
                                Edit</a><a class="btn btn-danger" asp-action="Delete" asp-route-id="@prd.ProductId">
                                <i class="fa fa-trash"></i>
                                Delete</a>
                            <a class="btn btn-info" target="_blank" asp-area="" asp-controller="Product" asp-action="Get" asp-route-id="@prd.ProductId">
                                <i class="fa fa-search"></i>
                                Web</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

StoreApp/Areas/Admin/Views/Product/Update.cshtml
@model ProductDtoForUpdate

<div class="text-center">
    <div class="display-6">Update</div>
</div>
<form method="post" asp-action="Update">
    
        <div class="text-danger" asp-validation-summary="All"></div>
        <input type="hidden" asp-for="ProductId"/>
    <div class="form-group my-3">
        <label asp-for="CategoryId"></label>
        <select class="form-control" asp-items="@ViewBag.Categories" asp-for="CategoryId">
        </select>
    </div>
    <div class="form-group my-3">
        <label asp-for="ProductName">Product Name</label>
        <input asp-for="ProductName" class="form-control" />
    </div>
    <div class="form-group my-3">
        <label asp-for="Price">Product Name</label>
        <input asp-for="Price" class="form-control" />
    </div>
    <div class="form-group my-3">
        <div class="btn-group">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-save"></i>
                Update
            </button>
            <a asp-action="Index" class="btn btn-outline-primary">
                <i class="fa fa-list"></i>
                Products
            </a>
        </div>
    </div>
</form>

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>
    <header>
        <partial name="_Navbar"/>
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer>
        @RenderSection("Footer", false)
        Footer
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark border-bottom navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a target="_blank" class="nav-link text-white" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

StoreApp/Views/Category/Index.cshtml
@model IEnumerable<Category>

    <div class="text-center my-3">
        <h6 class="display-6">
            Categories
        </h6>
    </div>
    <ul class="list-group my-3">
    @foreach (var cat in Model)
    {
        <li class="list-group-item">@cat.CategoryName</li>
    }
</ul>

StoreApp/Views/Home/Index.cshtml
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Document</title>
    </head>
    <body>
          <h1>Hello Store App</h1>
    </body>
    </html>

StoreApp/Views/Product/Get.cshtml
@model Product

<h3>@Model.ProductName</h3>
<p>@Model.Price</p>

<div class="btn-group">
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i>Home</a>
    <a class="btn btn-outline-primary" asp-controller="Product" asp-action="Index"><i class="fa-solid fa-list"></i>Products</a>
</div>


@section Header{
    <div>
        Header for only Get
    </div>
}

StoreApp/Views/Product/Index.cshtml
@model IQueryable<Product>

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoriesMenu")
    </div>
    <div class="col-md-9">
        <div class="row my-3">
            @foreach (Product prd in Model)
            {
                <partial name="_ProductCard" model="@prd" />
            }
        </div>
    </div>
</div>

@section Footer{
    <div>
        Only for Index Footer
    </div>
}


  

StoreApp/Views/Product/_ProductCard.cshtml
@model Product

<div class="col-sm-12 col-md-6 col-lg-4 my-2">
    <div class="card" style="width: 16rem;">
        <img src="/images/default.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.ProductName</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a asp-action="Get" asp-route-id="@Model.ProductId" class="btn btn-primary">
                <i class="fa-solid fa-arrow-right"></i>
                Go somewhere</a>
        </div>
    </div>
</div>

StoreApp/Views/Shared/Components/CategoriesMenu/Default.cshtml
@model IEnumerable<Category>
<div class="my-4">
    <ul class="list-group">
        @foreach (var cat in Model)
        {
            <li class="list-group-item">
                @cat.CategoryName
            </li>
        }
    </ul>
</div>

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-light border-bottom navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Store App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                <a class="nav-link active" aria-current="page" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
                <a class="nav-link active" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
            </div>
        </div>
    </div>
</nav>